/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bdd;

import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import java.sql.PreparedStatement;

/**
 *
 * @author SetyV
 */
public class AddStudent extends javax.swing.JPanel {
        private String IP = PanelPrincipal.IP;

    public AddStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TextApellido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textnia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TextCurso = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TextEdad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TextID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TextMatricula = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TextCiclo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(670, 670));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Speedee", 1, 24)); // NOI18N
        jLabel1.setText("Apellido");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        TextApellido.setText("Ingrese su apellido");
        add(TextApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 360, 30));

        jLabel2.setFont(new java.awt.Font("Speedee", 1, 24)); // NOI18N
        jLabel2.setText("Nombre");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        textNombre.setText("Ingrese su nombre");
        add(textNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 360, 30));

        jLabel3.setFont(new java.awt.Font("Speedee", 1, 24)); // NOI18N
        jLabel3.setText("NIA");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        textnia.setText("Ingrese su apellido");
        add(textnia, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 190, 30));

        jLabel5.setFont(new java.awt.Font("Speedee", 1, 24)); // NOI18N
        jLabel5.setText("Curso");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, -1, -1));

        TextCurso.setText("Ingrese su apellido");
        add(TextCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 210, 30));

        jLabel6.setFont(new java.awt.Font("Speedee", 1, 24)); // NOI18N
        jLabel6.setText("Edad");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        TextEdad.setText("Ingrese su apellido");
        add(TextEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 130, 30));

        jLabel7.setFont(new java.awt.Font("Speedee", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 199, 44));
        jLabel7.setText("ID Alumno");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        TextID.setText("Ingrese su apellido");
        add(TextID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 210, 30));

        jLabel8.setFont(new java.awt.Font("Speedee", 1, 24)); // NOI18N
        jLabel8.setText("Fecha de Matricula");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, -1));
        add(TextMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 210, 30));

        jLabel9.setFont(new java.awt.Font("Speedee", 1, 24)); // NOI18N
        jLabel9.setText("Ciclo");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        TextCiclo.setText("Ingrese su apellido");
        TextCiclo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(TextCiclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 210, 30));

        jButton1.setBackground(new java.awt.Color(218, 41, 28));
        jButton1.setFont(new java.awt.Font("McDonalds Helvetica", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Añadir a BDD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 550, 200, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try (Connection conexion = DriverManager.getConnection(IP, "root", "alumno");) {

            System.out.println("¡Conexión exitosa!");
            String query = "INSERT INTO alumnos(ID_Alumno, Nombre, Apellidos, Edad, NIA, Ciclo, Curso, Fecha_Matricula) VALUES("
                    + TextID.getText() + ","
                    + "'" + textNombre.getText() + "',"
                    + "'" + TextApellido.getText() + "',"
                    + TextEdad.getText() + ","
                    + textnia.getText() + ","
                    + "'" + TextCiclo.getText() + "',"
                    + "'" + TextCurso.getText() + "',"
                    + "'" + TextMatricula.getText() + "')";
            PreparedStatement preparedStatement = conexion.prepareStatement(query);

            int columnas = preparedStatement.executeUpdate();

            if (columnas > 0) {
                System.out.println("Usuario insertado correctamente.");
            } else {
                System.out.println("Error al insertar el usuario.");
            }

        } catch (SQLException ex) {
            Logger.getLogger(BDD.class.getName()).log(Level.SEVERE, null, ex);
        }
        
                

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextApellido;
    private javax.swing.JTextField TextCiclo;
    private javax.swing.JTextField TextCurso;
    private javax.swing.JTextField TextEdad;
    private javax.swing.JTextField TextID;
    private javax.swing.JTextField TextMatricula;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textnia;
    // End of variables declaration//GEN-END:variables
}
