/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bdd;

/**
 *
 * @author SetyV
 */
public class AddStudent extends javax.swing.JPanel {

    /**
     * Creates new form AddStudent
     */
    public AddStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(670, 670));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Speedee", 1, 24)); // NOI18N
        jLabel1.setText("Apellido");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        jTextField1.setText("Ingrese su apellido");
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 360, 30));

        jLabel2.setFont(new java.awt.Font("Speedee", 1, 24)); // NOI18N
        jLabel2.setText("Nombre");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        jTextField2.setText("Ingrese su nombre");
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 360, 30));

        jLabel3.setFont(new java.awt.Font("Speedee", 1, 24)); // NOI18N
        jLabel3.setText("Telefono");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, -1));

        jTextField3.setText("Ingrese su apellido");
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 190, 30));

        jLabel4.setFont(new java.awt.Font("Speedee", 1, 24)); // NOI18N
        jLabel4.setText("Correo Electronico");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 360, 30));

        jLabel5.setFont(new java.awt.Font("Speedee", 1, 24)); // NOI18N
        jLabel5.setText("Curso");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, -1, -1));

        jTextField5.setText("Ingrese su apellido");
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 210, 30));

        jLabel6.setFont(new java.awt.Font("Speedee", 1, 24)); // NOI18N
        jLabel6.setText("Edad");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        jTextField6.setText("Ingrese su apellido");
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 130, 30));

        jLabel7.setFont(new java.awt.Font("Speedee", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 199, 44));
        jLabel7.setText("ID Alumno");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        jTextField7.setText("Ingrese su apellido");
        add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 210, 30));

        jLabel8.setFont(new java.awt.Font("Speedee", 1, 24)); // NOI18N
        jLabel8.setText("Fecha de Matricula");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, -1, -1));
        add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 210, 30));

        jLabel9.setFont(new java.awt.Font("Speedee", 1, 24)); // NOI18N
        jLabel9.setText("Ciclo");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));

        jTextField9.setText("Ingrese su apellido");
        jTextField9.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 210, 30));

        jButton1.setBackground(new java.awt.Color(218, 41, 28));
        jButton1.setFont(new java.awt.Font("McDonalds Helvetica", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Añadir a BDD");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 550, 200, 50));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
