/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bdd;

/**
 *
 * @author Vespertino
 */
public class AlumnoMc extends javax.swing.JFrame {
    private String usuario1;
    private String password;
    
    public void setDatos(String usuario1, String password){
    this.usuario1=usuario1;
    this.password=password;
    }
    /**
     * Creates new form AlumnoMc
     */
    public AlumnoMc() {
        initComponents();
        
    }
    public void revalidar(){
    IvanGod.comprobarNotas(lblCiclo,lblCurso,lblNombre,lblNota1,lblNota2,lblNota3,lblNotaF,usuario1,password);

    }
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCurso = new javax.swing.JLabel();
        lblNota1 = new javax.swing.JLabel();
        lblCiclo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        Nota1 = new javax.swing.JLabel();
        Nota5 = new javax.swing.JLabel();
        Nota6 = new javax.swing.JLabel();
        Nota7 = new javax.swing.JLabel();
        lblNotaF = new javax.swing.JLabel();
        lblNota3 = new javax.swing.JLabel();
        lblNota2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 650));
        setMinimumSize(new java.awt.Dimension(900, 650));
        setPreferredSize(new java.awt.Dimension(900, 650));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 650));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCurso.setFont(new java.awt.Font("Speedee", 1, 24)); // NOI18N
        lblCurso.setText("Curso");
        jPanel1.add(lblCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        lblNota1.setBackground(new java.awt.Color(255, 51, 51));
        lblNota1.setFont(new java.awt.Font("Speedee", 1, 24)); // NOI18N
        lblNota1.setForeground(new java.awt.Color(255, 255, 255));
        lblNota1.setText("Nombre");
        lblNota1.setOpaque(true);
        jPanel1.add(lblNota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 100, 80));

        lblCiclo.setFont(new java.awt.Font("Speedee", 1, 24)); // NOI18N
        lblCiclo.setText("Ciclo");
        jPanel1.add(lblCiclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        lblNombre.setFont(new java.awt.Font("Speedee", 1, 24)); // NOI18N
        lblNombre.setText("Nombre");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        Nota1.setFont(new java.awt.Font("Speedee", 1, 24)); // NOI18N
        Nota1.setText("Nota Final");
        jPanel1.add(Nota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 120, 40));

        Nota5.setFont(new java.awt.Font("Speedee", 1, 24)); // NOI18N
        Nota5.setText("1ra Nota");
        jPanel1.add(Nota5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 120, 40));

        Nota6.setFont(new java.awt.Font("Speedee", 1, 24)); // NOI18N
        Nota6.setText("2da Nota");
        jPanel1.add(Nota6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 120, 40));

        Nota7.setFont(new java.awt.Font("Speedee", 1, 24)); // NOI18N
        Nota7.setText("3ra Nota");
        jPanel1.add(Nota7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 120, 40));

        lblNotaF.setBackground(new java.awt.Color(255, 51, 51));
        lblNotaF.setFont(new java.awt.Font("Speedee", 1, 24)); // NOI18N
        lblNotaF.setForeground(new java.awt.Color(255, 255, 255));
        lblNotaF.setText("Nombre");
        lblNotaF.setOpaque(true);
        jPanel1.add(lblNotaF, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 100, 80));

        lblNota3.setBackground(new java.awt.Color(255, 51, 51));
        lblNota3.setFont(new java.awt.Font("Speedee", 1, 24)); // NOI18N
        lblNota3.setForeground(new java.awt.Color(255, 255, 255));
        lblNota3.setText("Nombre");
        lblNota3.setOpaque(true);
        jPanel1.add(lblNota3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 100, 80));

        lblNota2.setBackground(new java.awt.Color(255, 51, 51));
        lblNota2.setFont(new java.awt.Font("Speedee", 1, 24)); // NOI18N
        lblNota2.setForeground(new java.awt.Color(255, 255, 255));
        lblNota2.setText("Nombre");
        lblNota2.setOpaque(true);
        jPanel1.add(lblNota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 100, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlumnoMc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlumnoMc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlumnoMc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlumnoMc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlumnoMc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nota1;
    private javax.swing.JLabel Nota5;
    private javax.swing.JLabel Nota6;
    private javax.swing.JLabel Nota7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCiclo;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNota1;
    private javax.swing.JLabel lblNota2;
    private javax.swing.JLabel lblNota3;
    private javax.swing.JLabel lblNotaF;
    // End of variables declaration//GEN-END:variables
}
