/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bdd;

import java.util.List;

/**
 *
 * @author Vespertino
 */
public class AlumnoMc extends javax.swing.JFrame {
    private int IdAlumno;
    private List<Object[]> datos;
    private int indiceActual = 0;

    
    public void setID(int ID){
    this.IdAlumno=ID;
    }
    
    public AlumnoMc() {
        initComponents();
        // cargarDatos(IdAlumno);
        
        
        
    }
     /*private void cargarDatos(int idAlumno) {
        NotasService service = new NotasService(idAlumno);
        this.datos = service.obtenerDatosCombinados();
    }*/
    public void actualizarVista(int direccion) {
        if(datos.isEmpty()) return;
        
        // Actualizar índice con límites circulares
        indiceActual = (indiceActual + direccion + datos.size()) % datos.size();
        
        Object[] registro = datos.get(indiceActual);
        
        // Asignar valores a los JLabels
        lbl1raNota.setText(String.format("%.2f", registro[0]));
        lbl2daNota.setText(String.format("%.2f", registro[1]));
        lbl3raNota.setText(String.format("%.2f", registro[2]));
        lblNotaF.setText(String.format("%.2f", registro[3]));
        
        lblNombre.setText("Quejarse con: "+"  "+Metodos.getNombreProfesor((int)registro[4]));
        lblModulos.setText("Módulo ID: " + registro[5]+" "+Metodos.getNombreModulo((int)registro[5]));
        lblCiclo.setText("Ciclo: " + registro[7]);
        lblCurso.setText("Curso: " + registro[8]);
    }
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCurso = new javax.swing.JLabel();
        lbl1raNota = new javax.swing.JLabel();
        lblCiclo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblModulos = new javax.swing.JLabel();
        Nota5 = new javax.swing.JLabel();
        Nota6 = new javax.swing.JLabel();
        Nota7 = new javax.swing.JLabel();
        lblNotaF = new javax.swing.JLabel();
        lbl3raNota = new javax.swing.JLabel();
        lbl2daNota = new javax.swing.JLabel();
        lblNombreAl = new javax.swing.JLabel();
        Nota2 = new javax.swing.JLabel();
        adelante = new javax.swing.JButton();
        atras = new javax.swing.JButton();
        iniciar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 650));
        setMinimumSize(new java.awt.Dimension(900, 650));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 650));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCurso.setFont(new java.awt.Font("Speedee", 1, 24)); // NOI18N
        lblCurso.setText("Curso :");
        jPanel1.add(lblCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 441, 190, 40));

        lbl1raNota.setBackground(new java.awt.Color(255, 51, 51));
        lbl1raNota.setFont(new java.awt.Font("Speedee", 1, 24)); // NOI18N
        lbl1raNota.setForeground(new java.awt.Color(255, 255, 255));
        lbl1raNota.setText("Nombre");
        lbl1raNota.setOpaque(true);
        jPanel1.add(lbl1raNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 100, 80));

        lblCiclo.setFont(new java.awt.Font("Speedee", 1, 24)); // NOI18N
        lblCiclo.setText("Ciclo :");
        jPanel1.add(lblCiclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 371, 180, 50));

        lblNombre.setFont(new java.awt.Font("Speedee", 1, 24)); // NOI18N
        lblNombre.setText("Nombre del Alumno");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 790, 40));

        lblModulos.setFont(new java.awt.Font("Speedee", 1, 24)); // NOI18N
        lblModulos.setText("Nota Final");
        jPanel1.add(lblModulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 450, 40));

        Nota5.setFont(new java.awt.Font("Speedee", 1, 24)); // NOI18N
        Nota5.setText("1ra Nota");
        jPanel1.add(Nota5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 120, 40));

        Nota6.setFont(new java.awt.Font("Speedee", 1, 24)); // NOI18N
        Nota6.setText("2da Nota");
        jPanel1.add(Nota6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 120, 40));

        Nota7.setFont(new java.awt.Font("Speedee", 1, 24)); // NOI18N
        Nota7.setText("3ra Nota");
        jPanel1.add(Nota7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 120, 40));

        lblNotaF.setBackground(new java.awt.Color(255, 51, 51));
        lblNotaF.setFont(new java.awt.Font("Speedee", 1, 24)); // NOI18N
        lblNotaF.setForeground(new java.awt.Color(255, 255, 255));
        lblNotaF.setText("Nombre");
        lblNotaF.setOpaque(true);
        jPanel1.add(lblNotaF, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 100, 80));

        lbl3raNota.setBackground(new java.awt.Color(255, 51, 51));
        lbl3raNota.setFont(new java.awt.Font("Speedee", 1, 24)); // NOI18N
        lbl3raNota.setForeground(new java.awt.Color(255, 255, 255));
        lbl3raNota.setText("Nombre");
        lbl3raNota.setOpaque(true);
        jPanel1.add(lbl3raNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 100, 80));

        lbl2daNota.setBackground(new java.awt.Color(255, 51, 51));
        lbl2daNota.setFont(new java.awt.Font("Speedee", 1, 24)); // NOI18N
        lbl2daNota.setForeground(new java.awt.Color(255, 255, 255));
        lbl2daNota.setText("Nombre");
        lbl2daNota.setOpaque(true);
        jPanel1.add(lbl2daNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 100, 80));

        lblNombreAl.setFont(new java.awt.Font("McDonalds Helvetica", 1, 18)); // NOI18N
        lblNombreAl.setForeground(new java.awt.Color(255, 51, 0));
        lblNombreAl.setText("NombreAl");
        jPanel1.add(lblNombreAl, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 180, 50));

        Nota2.setFont(new java.awt.Font("Speedee", 1, 24)); // NOI18N
        Nota2.setText("Nota Final");
        jPanel1.add(Nota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 120, 40));

        adelante.setText("Adelante");
        adelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adelanteActionPerformed(evt);
            }
        });
        jPanel1.add(adelante, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, 110, 50));

        atras.setText("Atras");
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        jPanel1.add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 523, 110, 50));

        iniciar.setText("Start");
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });
        jPanel1.add(iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, -1, -1));

        jLabel3.setFont(new java.awt.Font("McDonalds Helvetica", 1, 18)); // NOI18N
        jLabel3.setText("Habla pe Causa :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 180, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        actualizarVista(-1);
        // TODO add your handling code here:
    }//GEN-LAST:event_atrasActionPerformed

    private void adelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adelanteActionPerformed
    actualizarVista(1);        // TODO add your handling code here:
    }//GEN-LAST:event_adelanteActionPerformed

    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed
    
        this.datos = Metodos.obtenerDatosCombinados(this.IdAlumno);
        lblNombreAl.setText(Metodos.getNombreAl(this.IdAlumno));
        actualizarVista(0);        // TODO add your handling code here:
    }//GEN-LAST:event_iniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlumnoMc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlumnoMc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlumnoMc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlumnoMc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlumnoMc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nota2;
    private javax.swing.JLabel Nota5;
    private javax.swing.JLabel Nota6;
    private javax.swing.JLabel Nota7;
    private javax.swing.JButton adelante;
    private javax.swing.JButton atras;
    private javax.swing.JButton iniciar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl1raNota;
    private javax.swing.JLabel lbl2daNota;
    private javax.swing.JLabel lbl3raNota;
    private javax.swing.JLabel lblCiclo;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblModulos;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreAl;
    private javax.swing.JLabel lblNotaF;
    // End of variables declaration//GEN-END:variables
}
