
package bdd;

import bdd.AlumnoMc;
import bdd.PanelPrincipal;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Vespertino
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Principal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JLusuario = new javax.swing.JLabel();
        JLusuario1 = new javax.swing.JLabel();
        usuario1 = new javax.swing.JTextField();
        adminBoton = new javax.swing.JButton();
        buttonAlumno = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        campoContra = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel_Principal.setBackground(new java.awt.Color(218, 41, 28));
        Panel_Principal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Panel_Principal.setForeground(new java.awt.Color(80, 47, 89));
        Panel_Principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/mcdonaldo2.png"))); // NOI18N
        Panel_Principal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 120, 130));
        jLabel1.getAccessibleContext().setAccessibleDescription("");

        JLusuario.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        JLusuario.setForeground(new java.awt.Color(255, 199, 44));
        JLusuario.setText("CONTRASEÑA");
        Panel_Principal.add(JLusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 180, 50));

        JLusuario1.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        JLusuario1.setForeground(new java.awt.Color(255, 199, 44));
        JLusuario1.setText("USUARIO");
        Panel_Principal.add(JLusuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 130, 50));

        usuario1.setFont(new java.awt.Font("Perpetua", 2, 24)); // NOI18N
        usuario1.setText("Ingrese su nombre de usuario");
        usuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuario1ActionPerformed(evt);
            }
        });
        Panel_Principal.add(usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 420, 30));

        adminBoton.setText("Iniciar Sesion como Profesor");
        adminBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminBotonActionPerformed(evt);
            }
        });
        Panel_Principal.add(adminBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 200, 50));

        buttonAlumno.setText("Iniciar Sesion como Alumno");
        buttonAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAlumnoActionPerformed(evt);
            }
        });
        Panel_Principal.add(buttonAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 200, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/jaja.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        Panel_Principal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 310, 660));

        campoContra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoContra.setText("Lacontra");
        campoContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoContraActionPerformed(evt);
            }
        });
        Panel_Principal.add(campoContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 420, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuario1ActionPerformed

    private void campoContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoContraActionPerformed

    private void adminBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminBotonActionPerformed
       String user = usuario1.getText();
        // Mantengo la contraseña
        char [] contraseña  = campoContra.getPassword();
        String password = new String (contraseña);
        // Aplico MD5
        String passwordReal = Metodos.cifrarMD5(password);
        // Creo la interfaz Alumno
        if(Metodos.obtenerIdProfPC(user, passwordReal)>0){
        PanelPrincipal prof = new PanelPrincipal();
         prof.setIDprof(Metodos.obtenerIdProfPC(user, passwordReal));

        //al.setID(Metodos.obtenerIdAlPC(user, passwordReal));
        prof.setVisible(true);
        dispose();}else{
        JOptionPane.showMessageDialog(null, "Eres un gil");}
           // TODO add your handling code here:
    }//GEN-LAST:event_adminBotonActionPerformed

    private void buttonAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAlumnoActionPerformed
        String user = usuario1.getText();
        // Mantengo la contraseña
        char [] contraseña  = campoContra.getPassword();
        String password = new String (contraseña);
        // Aplico MD5
        String passwordReal = Metodos.cifrarMD5(password);
        // Creo la interfaz Alumno
        if(Metodos.obtenerIdAlPC(user, passwordReal)>0){
        AlumnoMc al = new AlumnoMc();
        al.setID(Metodos.obtenerIdAlPC(user, passwordReal));
        al.setVisible(true);
        dispose();}else{
        JOptionPane.showMessageDialog(null, "Eres un gil");
        }
        
        
        
    }//GEN-LAST:event_buttonAlumnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLusuario;
    private javax.swing.JLabel JLusuario1;
    private javax.swing.JPanel Panel_Principal;
    private javax.swing.JButton adminBoton;
    private javax.swing.JButton buttonAlumno;
    private javax.swing.JPasswordField campoContra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField usuario1;
    // End of variables declaration//GEN-END:variables
}
