/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bdd;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author Vespertino
 */
public class PanelPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public PanelPrincipal() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Principal = new javax.swing.JPanel();
        listar = new javax.swing.JButton();
        addStudent = new javax.swing.JButton();
        killStudent = new javax.swing.JButton();
        modifyStudent = new javax.swing.JButton();
        listar1 = new javax.swing.JButton();
        alv = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 664));

        Panel_Principal.setBackground(new java.awt.Color(218, 41, 28));
        Panel_Principal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Panel_Principal.setForeground(new java.awt.Color(80, 47, 89));
        Panel_Principal.setPreferredSize(new java.awt.Dimension(900, 664));
        Panel_Principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listar.setBackground(new java.awt.Color(38, 79, 54));
        listar.setText("Logout");
        listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarActionPerformed(evt);
            }
        });
        Panel_Principal.add(listar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 80, 70));

        addStudent.setBackground(new java.awt.Color(38, 79, 54));
        addStudent.setFont(new java.awt.Font("McDonalds Helvetica", 0, 12)); // NOI18N
        addStudent.setForeground(new java.awt.Color(255, 200, 54));
        addStudent.setText("Añadir Estudiante");
        addStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentActionPerformed(evt);
            }
        });
        Panel_Principal.add(addStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 220, 70));

        killStudent.setBackground(new java.awt.Color(38, 79, 54));
        killStudent.setFont(new java.awt.Font("McDonalds Helvetica", 1, 12)); // NOI18N
        killStudent.setForeground(new java.awt.Color(255, 200, 54));
        killStudent.setText("Eliminar Estudiante");
        killStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                killStudentActionPerformed(evt);
            }
        });
        Panel_Principal.add(killStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 220, 70));

        modifyStudent.setBackground(new java.awt.Color(38, 79, 54));
        modifyStudent.setFont(new java.awt.Font("McDonalds Helvetica", 0, 12)); // NOI18N
        modifyStudent.setForeground(new java.awt.Color(255, 200, 54));
        modifyStudent.setText("Modificar Estudiante");
        modifyStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyStudentActionPerformed(evt);
            }
        });
        Panel_Principal.add(modifyStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 220, 70));

        listar1.setBackground(new java.awt.Color(38, 79, 54));
        listar1.setFont(new java.awt.Font("McDonalds Helvetica", 1, 12)); // NOI18N
        listar1.setForeground(new java.awt.Color(255, 200, 54));
        listar1.setText("Listar Estudiantes");
        listar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listar1ActionPerformed(evt);
            }
        });
        Panel_Principal.add(listar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 220, 70));

        javax.swing.GroupLayout alvLayout = new javax.swing.GroupLayout(alv);
        alv.setLayout(alvLayout);
        alvLayout.setHorizontalGroup(
            alvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        alvLayout.setVerticalGroup(
            alvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        Panel_Principal.add(alv, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 670, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listarActionPerformed

    private void addStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentActionPerformed

        showCsm(new AddStudent());

    }//GEN-LAST:event_addStudentActionPerformed

    private void killStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_killStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_killStudentActionPerformed

    private void modifyStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyStudentActionPerformed

    private void listar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void showCsm(JPanel jp){
        jp.setSize(670, 670);
        jp.setLocation(0,0);
        
        alv.removeAll();
        alv.add(jp, BorderLayout.CENTER);
        alv.revalidate();
        alv.repaint();
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Principal;
    private javax.swing.JButton addStudent;
    private javax.swing.JPanel alv;
    private javax.swing.JButton killStudent;
    private javax.swing.JButton listar;
    private javax.swing.JButton listar1;
    private javax.swing.JButton modifyStudent;
    // End of variables declaration//GEN-END:variables
}
